### ISSUE TITLE
make grsecurity kernel, grsecurity-installer work inside Qubes-Whonix

### ISSUE THREAD

**Issue by adrelanos** [Whonix/grsecurity-installer#1]
**Introduction**:
- [grsecurity-installer](https://github.com/Whonix/grsecurity-installer)
- (a fork of https://github.com/rickard2/grsecurity-Debian-Installer)
- Used by and useful for the Linux distribution [Whonix](https://www.whonix.org), which is primarily run inside virtual machines

**TODO**:
- use [grsecurity sources from Debian repository](https://packages.debian.org/source/jessie-backports/linux-grsec) (not from grsecurity.net because then we can avoid custom gpg verification)
- package needs more testing and eventually various fixes
- the 'make menuconfig' which currently needs manual interaction needs to be automated (preseeded by a configuration file most likely?)
- sane, secure, useful kernel compilation configuration file required
- never mind MPROTECT for now (can be disabled)
- test if it works inside [Qubes](https://www.qubes-os.org) and fix if required
- test if it works inside [Qubes-Whonix](https://www.whonix.org/wiki/Qubes) and fix if required

**possibly helpful**:
- https://github.com/coldhakca/coldkernel - grsecurity for xen
- http://www.webcitation.org/6hG9TVlld - previous work and previous ticket discussion

**Bounty too low?**:

1) Go to https://www.bountysource.com/issues/14471558-make-grsecurity-kernel-grsecurity-installer-work-inside-whonix
2) Click on "Developers"
3) Click on "Get Started"
4) Select Status "Bounty too low"
5) Enter your offer and press "Save".

---

Mirrored from:
https://phabricator.whonix.org/T301

---

Mirrored to:
https://github.com/Whonix/grsecurity-installer/issues/1

---

On bountysource:
https://www.bountysource.com/issues/14471558-make-grsecurity-kernel-grsecurity-installer-work-inside-whonix

(If you are reading on bountysouce, you can skip all comments until `Snapshot of this before I am going to rewrite the ticket.` and read from there.)

**Comment by igorastds** [comment]
actual? I'm messing with grsecurity porting for over two months' evenings, can bring some help :)

**Comment by adrelanos** [comment]
Yes, this is still up to date as is.

**Comment by derlaft** [comment]
Hello.

I could not register on habricator.whonix.org, so I will comment here.

I have started working on the issue. Getting Whonix to work with gsec will require packaging https://github.com/hestinger/paxd to debian. Would writing a debian package script be enough, or should I bring it to some repository?

>fix compatibility with with VirtualBox guest additions installed (likely needs to be integrated with the usual automated kernel module (re-)compilation dkms)

This is fixed by 43ae4d3e976f4b916c274b6ed027cbb337f077e4. Moreover, [specific kernel options](https://www.proteansec.com/linux/running-virtualboxvmware-hardened-gentoo/) are required for kernel to work

**Comment by adrelanos** [comment]
* habricator.whonix.org -> https://phabricator.whonix.org/. But nevermind. Discussing this here is fine.
* https://github.com/hestinger/paxd -> https://github.com/thestinger/paxd
* https://www.proteansec.com/linux/running-virtualboxvmware-hardened-gentoo/ doesn't mention paxd being required.

We wouldn't have anyone to maintain a paxd Debian package in the long run. Can paxd be somehow avoided? It's just 'make menuconfig' that needs to be configured and automated?

**Comment by derlaft** [comment]
> https://www.proteansec.com/linux/running-virtualboxvmware-hardened-gentoo/ doesn't mention paxd being required.

That's because in Gentoo PaX attributes are set in ebuild manifests. For example, see [line 367](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/www-client/firefox/firefox-39.0.3.ebuild?revision=1.1&view=markup).

>Can paxd be somehow avoided? It's just 'make menuconfig' that needs to be configured and automated?

The problem is that lots of software (like libffi (btw, the problem is fixed in mainstream libffi in 2014, it's just debian being so slow), kdeinit4, kate, plasma-desktop, firefox, and [lots of other](https://raw.githubusercontent.com/thestinger/paxd/master/paxd.conf)) are not compatible with MPROTECT.
As I understand, there are three ways to cope with this problem:
* Completely disable PAX_MPROTECT
* Set PaX attrs at package time, which is impossible since Debian does not care about gsec. It is probably possible to set this attrs by some dpkg hooks by using that paxd.conf, but Tor browser in Whonix is installed not from .deb packages.
* Use paxd to watch filesystem and set PaX attributes if they are dropped, for example, by reinstallation of package

**Comment by adrelanos** [comment]
>> fix compatibility with with VirtualBox guest additions installed (likely needs to be integrated with the usual automated kernel module (re-)compilation dkms)

> This is fixed by 43ae4d3. Moreover, specific kernel options are required for kernel to work

What if we left VirtualBox out of this. Could we avoid paxd then or is it generally required?

**Comment by derlaft** [comment]
There are no (serious non-fixable) problems with virtualbox if kernel is properly configured. 

The problem is in other software (tons of kde apps, firefox, some libraries, as I mentioned earlier) that should be white-listed by setting pax attrs OR PAX_MPROTECT should be disabled in kernel configuation

**Comment by adrelanos** [comment]
How much security (if possible to quantify) do we loose if we "completely disable PAX_MPROTECT, and probably some other major features"?

Or in other words, how much added security by grsecurity do we get if we disable "completely disable PAX_MPROTECT, and probably some other major features"?

How realistic is it to get the pax policy in place anyway? Covered by your offer? And it also would have to be kept maintained, like apparmor profiles? Is the attempt to write a pax policy comparable to write AppArmor profiles for all or all major Debian packages?

**Comment by derlaft** [comment]
>How realistic is it to get the pax policy in place anyway? Covered by your offer? And it also would have to be kept maintained, like apparmor profiles? Is the attempt to write a pax policy comparable to write AppArmor profiles for all or all major Debian packages?

Writing whitelist rules is super-easy: if you see that an app is killed on start, you disable MPROTECT for it. However, it's just impossible to take into account all the debian packages. Of course that list would need maintenance. Archlinux paxd.conf is pretty good maintained, but Debian has different paths. 

>How much security (if possible to quantify) do we loose if we "completely disable PAX_MPROTECT, and probably some other major features"?

Hmm. Archlinux seems not tot enable MPROTECT until paxd is installed. If no other feautre requires serious whitelisting (I have to test it), it would be much easier and realistic to disable MPROTECT. Anyway, the most important component in Whonix is tor-browser and it does not support this feature.

**Comment by adrelanos** [comment]
Since we have no one available to maintain paxd... I.e. If security issues were ever reported against it, no one could fix those. So I would say for the first iteration (competition of this ticket), keep MPROTECT optional. Keep it easy to enable oneself as advanced user. What I mean, that way it should be easier for you to implement this.

Yes, please check what other features require whitelisting.

**Comment by derlaft** [comment]
Well, shit. 

[Grsecurity is going to restrict access to non-stable patches](https://grsecurity.net/announce.php)

Non-stable patches are great, but not for Whonix, because (stable) Debian `virtualbox-guest-dkms` package is not updated to support the most recent kernel.
It is possible to install sid repo into the system and lower it's priority to install only necessary packages from it. I am not sure if it is a good idea.

>Yes, please check what other features require whitelisting.

It seems that everything else works OK.

**Comment by adrelanos** [comment]
Yes, that's bad news. But now need to give up just now. Please continue working on the unstable grsecurity kernel.

The sponsor of this bounty will be trying to become a sponsor of grsecurity. Thereby getting access to stable patches. We would like to include you in this access as well if possible, so you can continue working on stable grsecurity kernels also. You'll be cc'd an e-mail where we mail spender @ grsecurity about this very soon.

**Comment by derlaft** [comment]
OK.

**Comment by derlaft** [comment]
>automate sane gpg verification, port to gpg-bash-lib

Done via 6f4502df4f5f92f8c063a9bdc836931fef5aad10

>fix compatibility with with VirtualBox guest additions installed (likely needs to be integrated with the usual automated kernel module (re-)compilation dkms)

Finally fixed by ffdf204ae4db10ddefb3339e75d82508b1651bc5

I am still working on the rest

**Comment by derlaft** [comment]
Sorry for delay, I've returned to this issue.

If you want me to test in on stable grsecurity kernels, I need an access to them.

**Comment by HulaHoopWhonix** [comment]
A lot happened in this space. Please see https://phabricator.whonix.org/T203 to get up to speed.

We are working on getting paxrat a paxd similar daemon written in Go from SubgraphOS for Debian packaging and expanding the exceptions list. Your help would be great.

**Comment by derlaft** [comment]
So, there is no need for grsecurity-installer now, right?

**Comment by adrelanos** [comment]
Alexey Derlaft:
> So, there is no need for grsecurity-installer now, right?

Impossible to say yet. It depends on if
https://phabricator.whonix.org/T203 can become a solution that really
works for Whonix. If we still need to compile our own kernel, we are
totally back to this ticket.

Also, this ticket involved more than securely downloading grsecurity. So
that's still on.

I'll contact the sponsor to figure out if stable patches matter and will
reply again. That may depend on if and if yes, how reliably the unstable
kernel would work for Whonix.

**Comment by HulaHoopWhonix** [comment]
Technically there is still a security benefit from building the package locally (https://wiki.archlinux.org/index.php/Grsecurity):

```
Some features like the RANDSTRUCT plugin and hiding symbol addresses are only truly useful with a custom kernel, since the pre-built kernel is available for analysis by any attacker. The linux-grsec package enables CONFIG_RANDOMIZE_BASE, but a custom build can provide unique symbol offsets in addition to the randomized base, making CONFIG_GRKERNSEC_HIDESYM valuable.
```

Debian provides source packages in unstable too so it would be a matter of creating a script that talks to dpkg - building and installing the package. This would provide all the security pros that a custom build would have but without the complexity of the original grsecurity-installer project.

**Comment by adrelanos** [comment]
Since it's just a single package that requires compiling...? Perhaps in
this case 'apt-get --compile' would do to get these benefits?

(No, 'apt-get --compile' is not a replacement for apt-build and/or
https://www.bountysource.com/issues/9115540-build-debian-packages-from-source-code
- but let's not go too much off topic.)

**Comment by HulaHoopWhonix** [comment]
Yes.

**Comment by HulaHoopWhonix** [comment]
Here is an example - but we let GPG verify of course:

https://askubuntu.com/a/246721

**Comment by adrelanos** [comment]
apt-get source already includes apt-get's gpg verification. Exit code
verification should be enough. But that should be tested if that
actually works. No further verification required. There is a confusing
message about missing keys, read about that here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=724744

**Comment by HulaHoopWhonix** [comment]
Additonally these lines need to be added:

deb-src http://security.debian.org unstable/updates main contrib non-free
deb-src http://ftp.us.debian.org/debian unstable main contrib non-free

sudo apt-get install debhelper quilt kernel-wedge gcc-5 gcc-5-plugin-dev patchutils xmlto build-essential

Import Yves's key to verify source pkg.

gpg --keyserver hkp://qdigse2yzvuglcix.onion --recv-keys 4510DCB57ED4704060C6647630550F7871EF0BA8

sudo apt-get source linux-grsec
cd linux-grsec*
dpkg-buildpackage

If we were based on testing these dependencies would be satisfied/already installed and the build process successfully starts. At the moment forcing their install with apt-pinning 
ends up upgrading most core libs anyway.

The following packages have unmet dependencies:
 gcc-5 : Depends: cpp-5 (= 5.3.1-5) but it is not going to be installed
         Depends: libcc1-0 (>= 5.3.1-5) but it is not going to be installed
         Depends: binutils (>= 2.25.90.20160101) but 2.25-5 is to be installed
         Depends: libgcc-5-dev (= 5.3.1-5) but it is not going to be installed
         Depends: libmpfr4 (>= 3.1.3) but 3.1.2-2 is to be installed

**Comment by adrelanos** [comment]
HulaHoopWhonix:
> Import Yves's key to verify source pkg.
> 
> gpg --keyserver hkp://qdigse2yzvuglcix.onion --recv-keys 4510DCB57ED4704060C6647630550F7871EF0BA8

It does not hurt as additional check, but 'apt-get source' already
verified it against the apt signing key as explained above. Something
worth documenting.

**Comment by adrelanos** [comment]
@derlaft:

> So, there is no need for grsecurity-installer now, right?

There is. Please continue working on this ticket. Please concentrate on unstable grsecurity patches for now.

Up to you for now to decide if using the grsecurity patches download mechanism that we have now or using Debian's new linux-grsec package. If you decide for the latter, please don't remove the code for the former, leave that as option, we might need it in future.

The bounty for this task can be increased. Please set a goal and if it sounds good I will be accepting it.

[Just to get the foot into the door. If we care about stable grsecurity patches we will create a separate [and perhaps bounty] for it.]

> I can help with paxrat, but not with it's Debian packaging.

Okay. I will likely create a separate ticket [and bounty] to have it packaged.

**Comment by adrelanos** [comment]
There is a similar project:
https://github.com/coldhakca/coldkernel
Having had a glimpse at the code, it is still missing tons of required features. The ones listed in this ticket. Still good to know. Thanks to @HulaHoopWhonix for mentioning it. I'll reach out to see if we can cooperate.

**Comment by adrelanos** [comment]
https://github.com/coldhakca/coldkernel/issues/27

**Comment by derlaft** [comment]
>There is. Please continue working on this ticket. Please concentrate on unstable grsecurity patches for now.

Actually, most of it is done. I only have to check kernel configuration, and test it on cubes/lxc

>fix various apparmor denied messages [1]

Could not find any. Can you give an example?

>Coldkernel
>GIDs

And, probably, add necessary groups.

**Comment by adrelanos** [comment]
> Actually, most of it is done. I only have to check kernel configuration, and test it on cubes/lxc

Good.

LXC is not required. [Qubes-Whonix](https://www.whonix.org/wiki/Qubes) is required.

> fix various apparmor denied messages [1]
>> Could not find any. Can you give an example?

Install Whonix AppArmor profiles. Just three commands to copy and paste. Instructions here:
https://www.whonix.org/wiki/AppArmor

(In Qubes-Whonix you need instructions to enable them but that is simple and covered in [Qubes-Whonix installation instructions](https://www.whonix.org/wiki/Qubes/Install).)

(In Qubes you need to install packages in the whonix-gw / whonix-ws TemplateVMs. Then shut down the emplate VMs and any VMs based on them. Then restart the TemplateBasedVMs and they will have the packages.)

**Comment by HulaHoopWhonix** [comment]
@derlaft Please check the virtualization configuration branch for  patches: https://github.com/Phoul/coldkernel/tree/virt_support/virt

@adrelanos Feel free to publicly share cooperation status of coldkernel if allowed.

**Comment by Phoul** [comment]
> https://github.com/Phoul/coldkernel/tree/virt_support/virt

Just a note, this has been moved to our primary repo at https://github.com/coldhakca/coldkernel/tree/virt_support. Anything under Phoul/coldkernel is used for our automated build testing, and the commit log will not be as clean as anything on the primary repo.

**Comment by adrelanos** [comment]
Snapshot of this before I am going to rewrite the ticket.

http://www.webcitation.org/6hG9TVlld

**Comment by adrelanos** [comment]
This is no longer possible, because grsecurity is now closed source.
